//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        public StudentTable()
        {

        }

        public StudentTable(int id, string firstName, string lastName, int balance, int acct, int pin, string bitmapImage)
        {
            this.id = id;
            this.firstName = firstName;
            this.lastName = lastName;
            this.balance = balance;
            this.acctNo = acct;
            this.pin = pin;
            this.image = bitmapImage;
        }

        public int id { get; set; }
        public int acctNo { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int pin { get; set; }
        public int balance { get; set; }
        public string image { get; set; }
    }
}
