//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatabaseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account(int id, string firstName, string lastName, decimal balance, string acctNo, string pin, byte[] image)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
            Balance = balance;
            AcctNo = acctNo;
            Pin = pin;
            Image = image;
        }

        public Account()
        {

        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal Balance { get; set; }
        public string AcctNo { get; set; }
        public string Pin { get; set; }
        public byte[] Image { get; set; }
    }
}
